version: '3.8'

networks:
  my-symfony:
    driver: bridge

services:
  # nginx
  nginx:
    build:
      context: ./docker-files/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - my-symfony
    volumes:
      - ./app:${APP_DIR_IN_CONTAINER:-/app}
      - ./docker-files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  # php
  php:
    build:
      context: ./docker-files/php
      args:
        app_dir: ${APP_DIR_IN_CONTAINER:-/app}
      dockerfile: Dockerfile
    container_name: php
    restart: on-failure
    user: 1000:1000
    ports:
      - "9000:9000"
    networks:
      - my-symfony
    volumes:
      - ./app:${APP_DIR_IN_CONTAINER:-/app}:rw,cached
    depends_on:
      - database
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined
      - host.docker.internal:host-gateway
  # mysql
  database:
    image: postgres:12
    container_name: database
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret321}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_DB: ${DB_NAME:-symfony-real}
    ports:
      - "5432:5432"
    networks:
      - my-symfony
